config/routes.rb
Rails.application.routes.draw do
  resources :destination_categories

  resources :destination_types

  resources :destinations

  resources :cities

end

app/models/destination_category.rb
class DestinationCategory < ActiveRecord::Base

	has_many :destination_types
	has_many :destinations, through: :destination_types
end

app/controllers/destination_categories_controller.rb
class DestinationCategoriesController < ApplicationController
  before_action :set_destination_category, only: [:show, :edit, :update, :destroy]

  # GET /destination_categories
  # GET /destination_categories.json
  def index
    @destination_categories = DestinationCategory.all
  end

  # GET /destination_categories/1
  # GET /destination_categories/1.json
  def show
  end

  # GET /destination_categories/new
  def new
    @destination_category = DestinationCategory.new
  end

  # GET /destination_categories/1/edit
  def edit
  end

  # POST /destination_categories
  # POST /destination_categories.json
  def create
    @destination_category = DestinationCategory.new(destination_category_params)

    respond_to do |format|
      if @destination_category.save
        format.html { redirect_to @destination_category, notice: 'Destination category was successfully created.' }
        format.json { render :show, status: :created, location: @destination_category }
      else
        format.html { render :new }
        format.json { render json: @destination_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destination_categories/1
  # PATCH/PUT /destination_categories/1.json
  def update
    respond_to do |format|
      if @destination_category.update(destination_category_params)
        format.html { redirect_to @destination_category, notice: 'Destination category was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination_category }
      else
        format.html { render :edit }
        format.json { render json: @destination_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destination_categories/1
  # DELETE /destination_categories/1.json
  def destroy
    @destination_category.destroy
    respond_to do |format|
      format.html { redirect_to destination_categories_url, notice: 'Destination category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination_category
      @destination_category = DestinationCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_category_params
      params.require(:destination_category).permit(:name)
    end
end

app/helpers/destination_categories_helper.rb
module DestinationCategoriesHelper
end

app/views/destination_categories/_form.html.erb
<%= form_for(@destination_category) do |f| %>
  <% if @destination_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination_category.errors.count, "error") %> prohibited this destination_category from being saved:</h2>

      <ul>
      <% @destination_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destination_categories/edit.html.erb
<h1>Editing destination_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination_category %> |
<%= link_to 'Back', destination_categories_path %>

app/views/destination_categories/index.html.erb
<h1>Listing destination_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @destination_categories.each do |destination_category| %>
      <tr>
        <td><%= destination_category.name %></td>
        <td><%= link_to 'Show', destination_category %></td>
        <td><%= link_to 'Edit', edit_destination_category_path(destination_category) %></td>
        <td><%= link_to 'Destroy', destination_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Destination category', new_destination_category_path %>

app/views/destination_categories/new.html.erb
<h1>New destination_category</h1>

<%= render 'form' %>

<%= link_to 'Back', destination_categories_path %>

app/views/destination_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @destination_category.name %>
</p>

<%= link_to 'Edit', edit_destination_category_path(@destination_category) %> |
<%= link_to 'Back', destination_categories_path %>