config/routes.rb
Rails.application.routes.draw do
  resources :destination_categories

  resources :destination_types

  resources :destinations

  resources :cities

end

app/controllers/destination_types_controller.rb
class DestinationTypesController < ApplicationController
  before_action :set_destination_type, only: [:show, :edit, :update, :destroy]

  # GET /destination_types
  # GET /destination_types.json
  def index
    @destination_types = DestinationType.all
  end

  # GET /destination_types/1
  # GET /destination_types/1.json
  def show
    @destination_type = DestinationType.find(params[:id])
  end

  # GET /destination_types/new
  def new
    @destination_type = DestinationType.new
  end

  # GET /destination_types/1/edit
  def edit
  end

  # POST /destination_types
  # POST /destination_types.json
  def create
    @destination_type = DestinationType.new(destination_type_params)

    respond_to do |format|
      if @destination_type.save
        format.html { redirect_to @destination_type, notice: 'Destination type was successfully created.' }
        format.json { render :show, status: :created, location: @destination_type }
      else
        format.html { render :new }
        format.json { render json: @destination_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destination_types/1
  # PATCH/PUT /destination_types/1.json
  def update
    respond_to do |format|
      if @destination_type.update(destination_type_params)
        format.html { redirect_to @destination_type, notice: 'Destination type was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination_type }
      else
        format.html { render :edit }
        format.json { render json: @destination_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destination_types/1
  # DELETE /destination_types/1.json
  def destroy
    @destination_type.destroy
    respond_to do |format|
      format.html { redirect_to destination_types_url, notice: 'Destination type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination_type
      @destination_type = DestinationType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_type_params
      params.require(:destination_type).permit(:destination_id, :destination_category_id)
    end
end

app/helpers/destination_types_helper.rb
module DestinationTypesHelper
end

app/views/destination_types/_form.html.erb
<%= form_for(@destination_type) do |f| %>
  <% if @destination_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination_type.errors.count, "error") %> prohibited this destination_type from being saved:</h2>

      <ul>
      <% @destination_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :destination_id %><br>
    <%= f.collection_check_boxes :destination_id, Destination.all, :id, :title do |b| %>
    <%= b.check_box %>
    <%= b.label %><br/>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :destination_category_id %><br>
    <%= f.collection_check_boxes :destination_category_id, DestinationCategory.all, :id, :name do |b| %>
    <%= b.check_box %>
    <%= b.label %><br/>
    <% end %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destination_types/edit.html.erb
<h1>Editing destination_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination_type %> |
<%= link_to 'Back', destination_types_path %>

app/views/destination_types/index.html.erb
<h1>Listing destination_types</h1>

<table>
  <thead>
    <tr>
      <th>Destination</th>
      <th>Destination category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @destination_types.each do |destination_type| %>
      <tr>
        <td><%= destination_type.destination_id %></td>
        <td><%= destination_type.destination_category_id %></td>
        <td><%= link_to 'Show', destination_type %></td>
        <td><%= link_to 'Edit', edit_destination_type_path(destination_type) %></td>
        <td><%= link_to 'Destroy', destination_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Destination type', new_destination_type_path %>

app/views/destination_types/new.html.erb
<h1>New destination_type</h1>

<%= render 'form' %>

<%= link_to 'Back', destination_types_path %>

app/views/destination_types/show.html.erb
<p id="notice"><%= notice %></p>




<p>
  <strong>Destination:</strong>
  <%= @destination_type.destination_category_id %>
</p>

<p>
  <strong>Destination category:</strong>
  <%= @destination_type.destination_category_id %>
</p>

<%= link_to 'Edit', edit_destination_type_path(@destination_type) %> |
<%= link_to 'Back', destination_types_path %>