config/routes.rb
Rails.application.routes.draw do
  resources :destination_categories

  resources :destination_types

  resources :destinations

  resources :cities

end

app/models/destination.rb
class Destination < ActiveRecord::Base

	belongs_to :city
	has_many :destination_types
	has_many :destination_categories, through: :destination_types
end

app/models/destination_type.rb
class DestinationType < ActiveRecord::Base

	belongs_to :destination 
	belongs_to :destination_category
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
    @destination = Destination.find(params[:id])
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:title, :city_id, :latitude, :longitude, destination_category_ids:[])
    end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.collection_select :city_id, City.all, :id, :name, {prompt: "select city"} %><br/>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>

  <div class= "field">
  <label>DestinationCategories</label><br/>
  <%= f.collection_check_boxes :destination_category_ids, DestinationCategory.all, :id, :name do |b| %>
  <%= b.check_box %>
  <%= b.label %>
  <br/>
   <% end %>
    

    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<h1>Listing destinations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>City</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @destinations.each do |destination| %>
      <tr>
        <td><%= destination.title %></td>
        <td><%= destination.city_id %></td>
        <td><%= destination.latitude %></td>
        <td><%= destination.longitude %></td>
        <td><%= link_to 'Show', destination %></td>
        <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
        <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

Name :
<% @destination.destination_categories.each do |category| %>
<%= category.name %>
<% end %>
<p>
  <strong>Title:</strong>
  <%= @destination.title %>
</p>

<p>
  <strong>City:</strong>
  <%= @destination.city_id %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @destination.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @destination.longitude %>
</p>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>